### PR TITLE
Update to the new pantsbuild fork of JarJarLinks

### PR DESCRIPTION
**Pull request by RadicalZephyr**
Pretty straightforward change it turns out.

It looks like the pantsbuild jarjar doesn't vendor the ASM version that it uses like it used to.

### CODE REVIEW

**Comment by benedekfazekas** [comment]
nice one. thanks. give me a couple of days to properly test this tho

**Comment by RadicalZephyr** [comment]
:+1: 

I was also looking at the java sources included in mranderson and comparing them to the equivalent classes in the newer version of jarjar and they look to be about 80% the same, so maybe we could change to using those instead as well?  Probably worth testing as well.

**Comment by bbatsov** [comment]
@RadicalZephyr Can you rebase this on top of the current `master`?

**Comment by RadicalZephyr** [comment]
@bbatsov rebased

I also took out some of the changes to project.clj to version numbers that were only related to me testing the changes locally.

**Comment by bbatsov** [comment]
@RadicalZephyr Looks good to me! I was about to merge this, but I'll leave that to @benedekfazekas. 

Thanks for looking into this!

**Comment by benedekfazekas** [comment]
did you get a chance to test this on cider-nrepl @bbatsov?

**Comment by bbatsov** [comment]
I went over the commit log of the project and everything looked good there. Didn't really have time to experiment with it, but it seems they've done some pretty good job maintaining and improving jarjar.

**Comment by benedekfazekas** [comment]
tested this with `cider-nrepl` as my main client :) when i run `source-deps` with version containing the PR I get
```
Exception in thread "main" java.lang.IllegalAccessError: tried to access class org.pantsbuild.jarjar.MainProcessor from class mranderson.util$apply_jarjar_BANG_
	at mranderson.util$apply_jarjar_BANG_.invokeStatic(util.clj:97)
	at mranderson.util$apply_jarjar_BANG_.invoke(util.clj:94)
	at leiningen.source_deps$source_deps.invokeStatic(source_deps.clj:315)
	at leiningen.source_deps$source_deps.doInvoke(source_deps.clj:287)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at clojure.lang.Var.invoke(Var.java:388)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
```

what am i missing?

**Comment by RadicalZephyr** [comment]
I... don't know.  I've looked at this a few times, and I'm pretty stumped as to what is happening.

At first I thought perhaps there was something wrong with the `org.pantsbuild/jarjar` jar, but it appears to have the `MainProcessor` class that cannot be found.

Interestingly, I also get that same error when trying to do anything with the changes in this PR.

What's strangest to me is that I get the _same error_ when I run `lein source-deps` on this changed branch of mranderson, even though the `project.clj` is referencing an older version of mranderson.  This seems very odd to me.  The only explanation I could come up with for that is that leiningen is actually loading the changed code instead of the version specified in `:plugins`, but not putting the new dependency on `org.pantsbuild/jarjar` on the classpath.

So next I tried creating a `0.4.10` release of mranderson where the only change was adding the pantsbuild jarjar as a dependency.  This built correctly.  I then tried to use this new version of mranderson to build a newer version of mranderson including the switch to using the pantsbuild/jarjar.  This fails with the same `IllegalAccessError` regarding the `MainProcessor` class.  This kind of busts my previous theory, but I thought I would write it all down in case it gives someone else any kind of insight.

**Comment by benedekfazekas** [comment]
https://github.com/benedekfazekas/mranderson/pull/18#issuecomment-421543373 i am guessing (remember would be a too strong word here) those java classes were there in the mranderson source to work around some access problems in jarjar. maybe this causing the problem again?

**Comment by benedekfazekas** [comment]
fixed by #51

**Pull request closed without merging**
